// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zjikzugsiaxxowksnzgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqaWt6dWdzaWF4eG93a3NuemdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTY4NjUsImV4cCI6MjA3NDE3Mjg2NX0.Oy0NZVerxkTp3F9nqTwBTevipnw2MyOjl_U9NlnWvqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);